theme = "space-villain"
icons = "awesome"

[[block]]
block = "net"
device = "enp5s0"
ip = false
speed_up = false
graph_up = true
interval = 5
use_bits = false

# [[block]]
# block = "notmuch"
# maildir = "/home/aaron/mail"
# query = "tag:unread and not tag:trash"
# threshold_warning = 1
# threshold_critical = 5
# name = ""
# name = ""

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "temperature"
chip = "zenpower-pci-00c3"
collapsed = false
interval = 5
format = "{min}°-{max}°"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"
device_kind = "sink"

[[block]]
block = "sound"
device_kind = "source"
# device = "alsa_input.usb-RODE_Microphones_RODE_NT-USB-00.iec958-stereo"
# device = "hw:1"
color_overrides = { warning_bg = "#ff0000" }


[[block]]
block = "bluetooth"
mac = "28:11:A5:35:50:04"
label = " QC35"

[[block]]
block = "time"
interval = 1
format = "%a %m/%d %R"
