theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "net"
device = "wnet0"
ssid = true
signal_strength = true
ip = false
graph_down = false
speed_down = false
speed_up = false
graph_up = false
interval = 5
use_bits = false
hide_missing = true

[[block]]
block = "net"
device = "net0"
ssid = false
signal_strength = false
ip = false
speed_up = false
speed_down = false
graph_up = false
interval = 5
use_bits = false
hide_missing = true

[[block]]
block = "disk_space"
path = "/home/aaron"
alias = "home"
info_type = "available"
show_percentage = true
interval = 30
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "bluetooth"
mac = "28:11:A5:35:50:04"
label = " QC35"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
